name: Java

on:
  push:
  workflow_dispatch:

jobs:
  build:
    permissions:
        checks: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
